#!/bin/bash
# 创建"鱼烧助手"快捷指令 — 用于语音和右键菜单触发
echo "🐱 鱼烧助手 — 快捷指令设置向导"
echo "=================================="
echo ""
echo "请在 Shortcuts.app 中创建名为「鱼烧助手」的快捷指令："
echo ""
echo "1. 打开 Shortcuts.app（快捷指令）"
echo "2. 点击 + 新建快捷指令"
echo "3. 命名为：鱼烧助手"
echo "4. 添加以下操作（可按需选择）："
echo ""
echo "   📝 基础版（语音备忘）："
echo "      - 「听写文本」→「显示结果」"
echo ""
echo "   📅 进阶版（语音创建日程）："
echo "      - 「听写文本」"
echo "      - 「获取日期」"
echo "      - 「添加新的日历事件」"
echo ""
echo "   💬 对话版（与鱼烧互动）："
echo "      - 「听写文本」"
echo "      - 「显示提醒」← Siri 语音回复"
echo ""
echo "5. 保存后，即可："
echo "   - 右键鱼烧 → ⚡ 快捷指令"
echo "   - 说「嘿 Siri，鱼烧助手」"
echo ""
echo "=================================="
echo "按 Enter 键打开 Shortcuts.app…"
read
open -a Shortcuts
